config/routes.rb
Jinglr::Application.routes.draw do
  root 'site#index'
  
  # Devise auth
  devise_for :users, controllers: {
    sessions: 'sessions',
    registrations: 'registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  devise_scope :user do
    delete 'logout' => 'sessions#destroy', as: :logout
    get 'login' => 'sessions#new', as: :login
    get 'register' => 'registrations#new', as: :register
    # Check for existence of username
    get 'username_check' => 'registrations#username_check', as: :username_check
  end
  
  # Users
  resources :user, controller: :users do
    resources :details, controller: :user_details
    
    member do
      post :upload_avatar
      delete :delete_avatar
      put :update_email
      put :update_password
      get :select_username
      put :set_username
    end
    
    collection do
      get :jingles
      get :favorites, controller: :jingle_favorites, to: :index
      get :notifications, controller: :notifications, to: :index
      get :followers, controller: :followers, to: :followers
      get :following, controller: :followers, to: :following
    end
  end
  
  # User home
  get 'user/jingles' => 'users#jingles', as: :home
  
  # Notificaitons in header
  get 'user/notifications/remote' => 'notifications#remote', as: :remote_notifications
  get 'user/notification/:id/remote' => 'notifications#remote_notification', as: :remote_notification
  # Mark notifications as viewed
  put 'user/notifications/view' => 'notifications#mark_all_viewed', as: :mark_notifications_viewed
  put 'user/notification/:id/view' => 'notifications#mark_viewed', as: :mark_notification_viewed
  put 'user/notifications/settings/update' => 'notifications#update_settings', as: :update_settings_notification
  
  # Jingles
  resources :jingles do
    resources :contributions, controller: :jingle_comments, only: [:index, :create, :destroy] do
      collection do
        get 'comments' => 'jingle_comments#comments', as: :comments
        get 'tracks' => 'jingle_comments#tracks', as: :tracks
      end
    end
    
    resources :likes, controller: :jingle_likes, only: [:create, :destroy] do
      collection do
        post :toggle
      end
    end
    resources :favorites, controller: :jingle_favorites, only: [:create, :destroy] do
      collection do
        post :toggle
      end
    end
    
    collection do
      post :add
      post :merge
      #get 'check-status' => 'jingles#check_status', as: :check_status
      #get 'merge-remote' => 'jingles#merge_remote', as: :merge_remote
      get 'new/:option' => 'jingles#new', as: :new_remote
      get 'sort/:sort' => 'jingles#index', as: :sorted
    end
    
    member do
      post 'toggle-follow' => 'jingles#toggle_follow', as: :toggle_follow
      put 'accept', as: :accept_merge
      put 'decline', as: :decline_merge
      get 'decline-confirm' => 'jingles#confirm_decline_merge', as: :confirm_decline_merge
      get 'check-status' => 'jingles#check_status', as: :check_status
      get 'check-track-status' => 'jingles#check_track_status', as: :check_track_status
      get 'merge-remote' => 'jingles#merge_remote', as: :merge_remote
      get 'add-track-remote' => 'jingles#add_track_remote', as: :add_track_remote
      get 'connections' => 'jingles#connections', as: :connections
      get 'new', as: :new_jingle_track
      get ':open' => 'jingles#show', as: :open
    end
  end
  
  # Track mixer
  resources :mixer, only: [:index, :show] do
    collection do
      get 'get/:jingle_id' => 'mixer#get_track', as: :mixer_get_track_remote
      put 'add' => 'mixer#add_track', as: :mixer_add_track_remote
      put 'remove/:jingle_id' => 'mixer#remove_track', as: :mixer_remove_track_remote
    end
  end
  
  # Feed
  get 'feed' => 'feeds#index', as: :feed
  get 'feed/sort/:sort' => 'feeds#index', as: :sorted_feed
  
  # Search
  get 'search' => 'search#show', as: :search
  get 'search/:q' => 'search#show'
  get 'search/:q/sort/:sort' => 'search#show', as: :sorted_search
  
  # Hashtags
  get 'hashtags' => 'hashtags#show', as: :hashtag_base
  get 'hashtags/:tag' => 'hashtags#show', as: :hashtag
  get 'hashtags/:tag/sort/:sort' => 'hashtags#show', as: :sorted_hashtag
  
  # Site
  get 'help' => 'site#help', as: :help
  get 'privacy' => 'site#privacy', as: :privacy
  get 'login_or_register' => 'site#login_or_register', as: :login_or_register
  get 'leave_feedback' => 'site#leave_feedback', as: :leave_feedback
  post 'leave_feedback' => 'site#leave_feedback_create', as: :leave_feedback_create
  # Catch 404 errors
  get '404' => 'site#error_404', as: :error_404
  #get '*path' => 'site#error_404', as: :error_404
  
  # Profiles
  post ':username/follow' => 'followers#toggle', as: :toggle_follow
  post ':username/follow-yes' => 'followers#create', as: :follow
  delete ':username/follow-no' => 'followers#destroy', as: :unfollow
  get ':username/followers' => 'profiles#followers', as: :profile_followers
  get ':username/following' => 'profiles#following', as: :profile_following
  get ':username' => 'profiles#show', as: :profile
  
  
end

app/controllers/mixer_controller.rb
class MixerController < ApplicationController
  before_filter :authenticate_user!
  respond_to :html, :js, :json
  helper_method :jingle
  
  def index
    #@jingles = Jingle.where({id: current_user.detail.track_mixer_list_array})
    # Can't use the nice 'where' AR method because if the user selects the same track twice,
    # it will only return one
    @jingles = []
    current_user.detail.track_mixer_list_array.each do |track|
      @jingles << Jingle.find(track)
    end
  end
  
  def show
    
  end
  
  def get_track
    render partial: "mixer/browser_track", locals: {jingle: jingle}
  end
  
  def add_track
    if current_user.add_track_to_mixer!(jingle)
      get_track
    else
      render text: t('track_mixer.errors.too_many_tracks'), status: :unprocessable_entity
    end
  end
  
  def remove_track
    if current_user.remove_track_from_mixer!(jingle)
      render nothing: true, status: :ok
    else
      render text: t('track_mixer.errors.remove_error'), status: :unprocessable_entity
    end
  end
  
protected
  def jingle
    @jingle ||= Jingle.find(params[:jingle_id])
  end
end

app/helpers/mixer_helper.rb
module MixerHelper
  def track_mixer_has_tracks?
    current_user.detail.track_mixer_list_array.length > 1
  end
  
  def track_mixer_has_track?
    current_user.detail.track_mixer_list_array.length > 0
  end

end

app/views/mixer/_browser_track.html.haml
%span.list-group-item.jingle
  %span.track-img{data: {toggle: "tooltip", placement: "bottom"}, title: truncate(jingle.desc, length: 65)}
    %span.name.label.bg-light= t('track_mixer.owner', user: link_to(jingle.user.display_name, profile_path(jingle.user.username))).html_safe
    = image_tag(jingle.waveform_url, alt: "Waveform")
  = icon_link("", {href: mixer_remove_track_remote_mixer_index_path(jingle), class: "btn btn-danger btn-sm track-delete", data: {method: :put, remote: true}}, "icon-remove")
  
:javascript
  $(document).ready(function() {
    fade_in_images();
    $("[data-toggle=tooltip]").tooltip();
  });

app/views/mixer/_track.html.haml
- @jingles = @jingles || nil
%div{id: "track_#{i}", data: {path: jingle.latest_url, waveform: jingle.waveform_url, duration: jingle.track_duration}}
= hidden_field_tag "jingle[tracks][#{jingle.id}#{'d' if @jingles && jingle.id == @jingles[i].id && i > 0}]", "0", id: "track_offset_#{i}"
.track{class: "track_#{i}"}
  .info
    .panel-body
      .clearfix
        = link_to(image_tag(jingle.user.avatar(:small), alt: jingle.user.display_name, title: jingle.user.display_name, class: "img-circle"), profile_path(jingle.user.username), class: "thumb-sm pull-left m-r")
        %small.text-muted
          = icon_link("", {href: jingle_path(jingle), class: "btn btn-info btn-xs m-b-xs view-track"}, "icon-music")
        - if request.path == mixer_index_path
          %small.text-muted
            = icon_link("", {href: mixer_remove_track_remote_mixer_index_path(jingle), class: "btn btn-danger btn-xs track-mixer-delete", data: {method: :put, remote: true, index: i}}, "icon-remove")
      .offset.label.bg-light.m-t-sm
        = t('track_mixer.index.track.offset')
        %span 0.000
  .jingle
    .track-img
      .progressbar-holder
        .progressbar
      = image_tag(jingle.waveform_url, alt: "Waveform", id: "waveform_#{i}")
      .pull-left.jingle-desc.label.bg-light= jingle.desc.blank? ? t('track_mixer.index.track.your_track') : jingle.desc

app/views/mixer/_track_processing.html.haml
.track.track-processing
  .jingle
    .generating_jingle.from_mixer
      %i.icon-spinner.icon-spin

:javascript
  $(document).ready(function() {
    jingleInterval = setInterval(checkJingleStatus, 3000);
    
    function checkJingleStatus() {
      $.get("#{add_track_remote_jingle_path(jingle)}", function(data) {
        $("<div>").load("#{add_track_remote_jingle_path(jingle)}", function() {
          clearInterval(jingleInterval);
          $("#mixer .panel-body.scrollable .track.track-processing").remove();
          $("#mixer .panel-body.scrollable script:last-child").remove();
          $("#mixer .panel-body.scrollable #track_1").remove();
          $("#mixer .panel-body.scrollable .track_1").remove();
          $("#mixer .panel-body.scrollable #track_offset_1").remove();
          $("#mixer .panel-body.scrollable").append($(this).html());
          fade_in_images();
          if ($tracks[1] == undefined) {
            if ($("#track_1").length > 0) {
              $tracks[1] = $("#track_1");
              mix.attachJPlayerObjects(1, $tracks[1]);
              mix.rebind(0, $tracks[0]);
            }
          }
        });
      });
    }
  });

app/views/mixer/index.html.haml
- content_for :title do
  = t('track_mixer.index.title')

- content_for :header do
  = render partial: "mixer/tour/index"

- if track_mixer_has_tracks?
  = form_tag merge_jingles_path, id: "track_mixer_form", method: :post, remote: true do
    .col-lg-12.m-t#mixer
      = render partial: "shared/beta", locals: {text: t('beta.track_mixer.index')}
      %h4= t('track_mixer.index.guide')
      .panel
        .panel-body.scrollable
          - @jingles.each_with_index do |jingle, i|
            = render partial: "mixer/track", locals: {jingle: jingle, i: i}
        %i.icon-arrow-right.pull-right.mixer-scroll-right
        %i.icon-arrow-left.pull-left.mixer-scroll-left{style: "display: none;"}
        .panel-body.text-center
          = icon_link("", {href: "#", class: "btn btn-info btn-lg track-play"}, "icon-play")
            
    
    .col-lg-12
      %textarea.form-control.input-lg.no-border{rows: "2", maxlength: "200",
        placeholder: "Describe this jingle", id: "jingle_desc_mixer", name: "jingle[desc]"}
    
    .col-lg-12.m-t
      .pull-right.m-b
        = link_to(t('buttons.cancel'), jingles_path, class: "btn btn-danger")
        %button{type: "submit", id: "merge-submit-button", class: "btn btn-success disabled"}
          %i.icon-beaker
          = t('buttons.merge')
- else
  %section.panel.no-borders.hbox
    %aside.bg-danger.clearfix.lter.r-r.text-right.v-middle
      .wrapper.h3.font-thin
        = t('track_mixer.index.empty_head')
    %aside
      .pos-rlt
        %span.arrow.left.hidden-xs
        .panel-body
          = t('track_mixer.index.empty').html_safe

#mixer-tracks-json

:javascript
  $(document).ready(function() {
    fade_in_images();
  });