config/routes.rb
Jinglr::Application.routes.draw do
  root 'site#index'
  
  # Devise auth
  devise_for :users, controllers: {
    sessions: 'sessions',
    registrations: 'registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  devise_scope :user do
    delete 'logout' => 'sessions#destroy', as: :logout
    get 'login' => 'sessions#new', as: :login
    get 'register' => 'registrations#new', as: :register
    # Check for existence of username
    get 'username_check' => 'registrations#username_check', as: :username_check
  end
  
  # Users
  resources :user, controller: :users do
    resources :details, controller: :user_details
    
    member do
      post :upload_avatar
      delete :delete_avatar
      put :update_email
      put :update_password
      get :select_username
      put :set_username
    end
    
    collection do
      get :jingles
      get :favorites, controller: :jingle_favorites, to: :index
      get :notifications, controller: :notifications, to: :index
      get :followers, controller: :followers, to: :followers
      get :following, controller: :followers, to: :following
    end
  end
  
  # User home
  get 'user/jingles' => 'users#jingles', as: :home
  
  # Notificaitons in header
  get 'user/notifications/remote' => 'notifications#remote', as: :remote_notifications
  get 'user/notification/:id/remote' => 'notifications#remote_notification', as: :remote_notification
  # Mark notifications as viewed
  put 'user/notifications/view' => 'notifications#mark_all_viewed', as: :mark_notifications_viewed
  put 'user/notification/:id/view' => 'notifications#mark_viewed', as: :mark_notification_viewed
  put 'user/notifications/settings/update' => 'notifications#update_settings', as: :update_settings_notification
  
  # Jingles
  resources :jingles do
    resources :contributions, controller: :jingle_comments, only: [:index, :create, :destroy] do
      collection do
        get 'comments' => 'jingle_comments#comments', as: :comments
        get 'tracks' => 'jingle_comments#tracks', as: :tracks
      end
    end
    
    resources :likes, controller: :jingle_likes, only: [:create, :destroy] do
      collection do
        post :toggle
      end
    end
    resources :favorites, controller: :jingle_favorites, only: [:create, :destroy] do
      collection do
        post :toggle
      end
    end
    
    collection do
      post :add
      post :merge
      #get 'check-status' => 'jingles#check_status', as: :check_status
      #get 'merge-remote' => 'jingles#merge_remote', as: :merge_remote
      get 'new/:option' => 'jingles#new', as: :new_remote
      get 'sort/:sort' => 'jingles#index', as: :sorted
    end
    
    member do
      post 'toggle-follow' => 'jingles#toggle_follow', as: :toggle_follow
      put 'accept', as: :accept_merge
      put 'decline', as: :decline_merge
      get 'decline-confirm' => 'jingles#confirm_decline_merge', as: :confirm_decline_merge
      get 'check-status' => 'jingles#check_status', as: :check_status
      get 'check-track-status' => 'jingles#check_track_status', as: :check_track_status
      get 'merge-remote' => 'jingles#merge_remote', as: :merge_remote
      get 'add-track-remote' => 'jingles#add_track_remote', as: :add_track_remote
      get 'connections' => 'jingles#connections', as: :connections
      get 'new', as: :new_jingle_track
      get ':open' => 'jingles#show', as: :open
    end
  end
  
  # Track mixer
  resources :mixer, only: [:index, :show] do
    collection do
      get 'get/:jingle_id' => 'mixer#get_track', as: :mixer_get_track_remote
      put 'add' => 'mixer#add_track', as: :mixer_add_track_remote
      put 'remove/:jingle_id' => 'mixer#remove_track', as: :mixer_remove_track_remote
    end
  end
  
  # Feed
  get 'feed' => 'feeds#index', as: :feed
  get 'feed/sort/:sort' => 'feeds#index', as: :sorted_feed
  
  # Search
  get 'search' => 'search#show', as: :search
  get 'search/:q' => 'search#show'
  get 'search/:q/sort/:sort' => 'search#show', as: :sorted_search
  
  # Hashtags
  get 'hashtags' => 'hashtags#show', as: :hashtag_base
  get 'hashtags/:tag' => 'hashtags#show', as: :hashtag
  get 'hashtags/:tag/sort/:sort' => 'hashtags#show', as: :sorted_hashtag
  
  # Site
  get 'help' => 'site#help', as: :help
  get 'privacy' => 'site#privacy', as: :privacy
  get 'login_or_register' => 'site#login_or_register', as: :login_or_register
  get 'leave_feedback' => 'site#leave_feedback', as: :leave_feedback
  post 'leave_feedback' => 'site#leave_feedback_create', as: :leave_feedback_create
  # Catch 404 errors
  get '404' => 'site#error_404', as: :error_404
  #get '*path' => 'site#error_404', as: :error_404
  
  # Profiles
  post ':username/follow' => 'followers#toggle', as: :toggle_follow
  post ':username/follow-yes' => 'followers#create', as: :follow
  delete ':username/follow-no' => 'followers#destroy', as: :unfollow
  get ':username/followers' => 'profiles#followers', as: :profile_followers
  get ':username/following' => 'profiles#following', as: :profile_following
  get ':username' => 'profiles#show', as: :profile
  
  
end

app/views/shared/_analytics.html.haml
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-2027752-15', 'jinglr.com');
  ga('send', 'pageview');

app/views/shared/_audio_player.html.haml
%ul.nav.navbar-nav.navbar-right.player-navbar
  %li
    /%audio#audio_player{style: "width: 100%;", controls: "control", preload: "none", src: "/", type: "audio/mpeg"}
    #audio_player
    #audio_player_container
      .track-img.jp-seek-bar
        .progress
        %img{src: asset_path("audio_player_bg.png"), data: {default: asset_path("audio_player_bg.png")}}
        .label.bg-light.current-time 0:00
      %button{type: "button", class: "btn btn-dark"}
        %i.icon-play
    #audio_player_details.bg-black
      = link_to(t('audio_player.view'), jingles_path)

app/views/shared/_beta.html.haml
.alert.alert-warning.alert-block
  %button.close{type: "button", data: {dismiss: "alert"}}
    %i.icon-remove
  %h4
    %i.icon-bug
    = t('beta.title')
  = text

app/views/shared/_breadcrumbs.html.haml
.col-lg-12
  %ul.breadcrumb
    - breadcrumbs do |links|
      - if links.any?
        - links.each do |link|
          %li{class: ('active' if link == links[-1])}
            = link_to(link.text, link.url)

app/views/shared/_browser.html.haml
- if content_for?(:browser)
  %aside.aside-md.bg-light.lters.b-r
    %section.vbox
      %section.scrollable#browser-sidebar
        .wrapper
          #above-track-mixer
            = yield :browser
          
          - if user_signed_in?
            .list-group.bg-white#track-mixer{data: {max: APP_CONFIG["track_mixer_max"], success: t('track_mixer.drop_tag'), error: t('track_mixer.too_many_tracks')}}
              .drop-overlay.bg-warning
                %span= current_user.detail.track_mixer_too_many_tracks? ? t('track_mixer.too_many_tracks') : t('track_mixer.drop_tag')
                
              %span.bg-dark.list-group-item
                = t('track_mixer.title')
                = icon_link("", {href: mixer_index_path, class: "btn btn-default btn-xs pull-right", id: "view-track-mixer-button", data: {error: t('track_mixer.errors.not_enough_tracks')}}, "icon-pencil")
                
              - if track_mixer_has_track?
                - current_user.detail.track_mixer_list_array.each do |i|
                  = render partial: "mixer/browser_track", locals: {jingle: Jingle.find(i)}

app/views/shared/_filter_date.html.haml
.panel.bg-white.m-b
  .panel-body.form-inline
    %label= t('filter.from')
    %input.input-sm.input-s.datepicker-input.form-control#sort-jingles-from{type: "text",
      value: params[:from] || (Time.now - 1.month).strftime("%m-%d-%Y"), size: "10", "data-date-format" => "mm-dd-yyyy"}
    %label= t('filter.to')
    %input.input-sm.input-s.datepicker-input.form-control#sort-jingles-to{type: "text",
      value: params[:to] || Time.now.strftime("%m-%d-%Y"), size: "10", "data-date-format" => "mm-dd-yyyy"}
    = link_to(t('buttons.do_it'), "#", class: "btn btn-info btn-sm", id: "sort-jingles-button")

app/views/shared/_flash_messages.html.haml
- if flash.notice
  .col-lg-12
    .alert.alert-success.m-t
      %button.close{type: "button", data: {dismiss: "alert"}}
        %i.icon-remove
      %i.icon-ok-sign
      = flash.notice
- if flash.alert
  .col-lg-12
    .alert.alert-danger.m-t
      %button.close{type: "button", data: {dismiss: "alert"}}
        %i.icon-remove
      %i.icon-ban-circle
      = flash.alert

app/views/shared/_header.html.haml
%header.header.bg-black.navbar.navbar-inverse
  .collapse.navbar-collapse.pull-in
    - if content_for?(:header)
      %ul.nav.navbar-nav.m-l-n
        = yield(:header)
      
    = render partial: "shared/user"
    
    %ul.nav.navbar-nav.navbar-right.search-navbar
      %li
        %a.dropdown-toggle#search_form{href: "#", data: {toggle: "dropdown"}}
          %i.icon-search.text-white
    
        %section.dropdown-menu.animated.fadeInUp.search-bar
          %section.panel
            = form_tag search_path, class: "navbar-form navbar-right m-t-sm", role: "search", method: :get do
              .form-group.bg-dark.search-fix
                .input-group.input-s-lg.input-append.m-sm
                  %input.form-control.input-sm.no-border.bg-dark{type: "text", placeholder: "Search", name: "q"}
                  %span.input-group-btn
                    %button.btn.btn-sm.btn-success.btn-icon{type: "submit"}
                      %i.icon-search

    = render partial: "shared/audio_player"

app/views/shared/_menu.html.haml
%nav.nav-primary.hidden-xs
  %ul.nav
    - if user_signed_in?
      - if allow_remote_create? && !current_user.username.blank?
        %li#create-button= icon_link(t('menu.new_jingle'), {href: new_remote_jingles_path('remote'), class: "lter", data: {toggle: "ajaxModal", modalclass: "new_jingle_modal"}}, "icon-plus")
      - else
        %li#create-button= icon_link(t('menu.new_jingle'), {href: new_jingle_path, class: "lter"}, "icon-plus")
    - else
      %li= icon_link(t('menu.new_jingle'), {href: login_or_register_path, class: "lter", data: {toggle: "ajaxModal", modalclass: "login_or_register"}}, "icon-plus")
    
    %li#home-button= icon_link(t('menu.home'), {href: root_path}, "icon-home")
    - if user_signed_in?
      %li#feed-button= icon_link(t('menu.feed'), {href: feed_path}, "icon-music")
    %li#discover-button= icon_link(t('menu.discover'), {href: jingles_path}, "icon-globe")

app/views/shared/_modal.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button{type: "button", class: "close", data: {dismiss: "modal"}} &times;
      %h4.modal-title= title
    .modal-body
      = render partial: partial_name
    - unless options[:ignore_footer]
      .modal-footer
        =link_to(t('buttons.cancel'), "#", class: "btn btn-danger", data: {dismiss: "modal"})
        =link_to(t('buttons.do_it'), button_ok, class: "btn btn-success modal-submit", data: {target: "modal-target"})

:javascript
  $(document).ready(function() {
    $('[data-dismiss="modal"]').on('click',function(e){
      $("#ajaxModal").detach();
    });
    
    if ($(".modal-dialog").parent().hasClass("new_jingle_modal")) {
      $('.modal-submit').addClass("disabled");
    }
  });

app/views/shared/_tour_template.html.haml
.popover
  .arrow
  %h3.popover-title
  .popover-content
  %nav.popover-navigation
    .btn-group
      %button.btn.btn-sm.btn-default{data: {role: 'prev'}} &laquo; #{t('buttons.prev')}
      %button.btn.btn-sm.btn-default{data: {role: 'next'}} #{t('buttons.next')} &raquo;
    %button.btn.btn-sm.btn-info{data: {role: 'end'}}= t('buttons.got_it')

app/views/shared/_user.html.haml
%ul.nav.navbar-nav.navbar-right
  - if user_signed_in? && !current_user.username.blank?
    %li.hidden-xs
      %a.dropdown-toggle#notifications_indicator{href: notifications_user_index_path, data: {toggle: "dropdown"}}
        %i.icon-bell-alt.text-white
        %span.badge.up.bg-info.m-l-n-sm#notifications_indicator_number{style: "#{'display: none;' unless current_user.notifications.unread?}"}= current_user.notifications.unread.count
  
      %section.dropdown-menu.animated.fadeInUp.notifications-bar
        
        
  - if user_signed_in?
    %li.dropdown
      %a.dropdown-toggle{href: "#", data: {toggle: "dropdown"}}
        %span.thumb-xs.avatar.pull-left.m-t-n-xs.m-r-xs#main-header-avatar
          = image_tag(current_user.avatar(:small), alt: current_user.display_name, id: "main-header-avatar-img")
        = current_user.display_name
        %b.caret
      %ul.dropdown-menu.animated.fadeInLeft
        %li= link_to(t('header.user.profile'), profile_path(current_user.username))
        %li= link_to(t('header.user.settings'), edit_user_path(current_user))
        %li.divider
        %li= link_to(t('header.user.help'), help_path)
        %li= link_to(t('header.user.feedback'), leave_feedback_path, data: {toggle: "ajaxModal"})
        %li.divider
        %li= link_to(t('header.user.logout'), logout_path, data: {method: :delete})
  - else
    %li= link_to(t('buttons.login'), login_path)
    %li= link_to(t('buttons.register'), register_path)