config/routes.rb
Jinglr::Application.routes.draw do
  root 'site#index'
  
  # Devise auth
  devise_for :users, controllers: {
    sessions: 'sessions',
    registrations: 'registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  devise_scope :user do
    delete 'logout' => 'sessions#destroy', as: :logout
    get 'login' => 'sessions#new', as: :login
    get 'register' => 'registrations#new', as: :register
    # Check for existence of username
    get 'username_check' => 'registrations#username_check', as: :username_check
  end
  
  # Users
  resources :user, controller: :users do
    resources :details, controller: :user_details
    
    member do
      post :upload_avatar
      delete :delete_avatar
      put :update_email
      put :update_password
      get :select_username
      put :set_username
    end
    
    collection do
      get :jingles
      get :favorites, controller: :jingle_favorites, to: :index
      get :notifications, controller: :notifications, to: :index
      get :followers, controller: :followers, to: :followers
      get :following, controller: :followers, to: :following
    end
  end
  
  # User home
  get 'user/jingles' => 'users#jingles', as: :home
  
  # Notificaitons in header
  get 'user/notifications/remote' => 'notifications#remote', as: :remote_notifications
  get 'user/notification/:id/remote' => 'notifications#remote_notification', as: :remote_notification
  # Mark notifications as viewed
  put 'user/notifications/view' => 'notifications#mark_all_viewed', as: :mark_notifications_viewed
  put 'user/notification/:id/view' => 'notifications#mark_viewed', as: :mark_notification_viewed
  put 'user/notifications/settings/update' => 'notifications#update_settings', as: :update_settings_notification
  
  # Jingles
  resources :jingles do
    resources :contributions, controller: :jingle_comments, only: [:index, :create, :destroy] do
      collection do
        get 'comments' => 'jingle_comments#comments', as: :comments
        get 'tracks' => 'jingle_comments#tracks', as: :tracks
      end
    end
    
    resources :likes, controller: :jingle_likes, only: [:create, :destroy] do
      collection do
        post :toggle
      end
    end
    resources :favorites, controller: :jingle_favorites, only: [:create, :destroy] do
      collection do
        post :toggle
      end
    end
    
    collection do
      post :add
      post :merge
      #get 'check-status' => 'jingles#check_status', as: :check_status
      #get 'merge-remote' => 'jingles#merge_remote', as: :merge_remote
      get 'new/:option' => 'jingles#new', as: :new_remote
      get 'sort/:sort' => 'jingles#index', as: :sorted
    end
    
    member do
      post 'toggle-follow' => 'jingles#toggle_follow', as: :toggle_follow
      put 'accept', as: :accept_merge
      put 'decline', as: :decline_merge
      get 'decline-confirm' => 'jingles#confirm_decline_merge', as: :confirm_decline_merge
      get 'check-status' => 'jingles#check_status', as: :check_status
      get 'check-track-status' => 'jingles#check_track_status', as: :check_track_status
      get 'merge-remote' => 'jingles#merge_remote', as: :merge_remote
      get 'add-track-remote' => 'jingles#add_track_remote', as: :add_track_remote
      get 'connections' => 'jingles#connections', as: :connections
      get 'new', as: :new_jingle_track
      get ':open' => 'jingles#show', as: :open
    end
  end
  
  # Track mixer
  resources :mixer, only: [:index, :show] do
    collection do
      get 'get/:jingle_id' => 'mixer#get_track', as: :mixer_get_track_remote
      put 'add' => 'mixer#add_track', as: :mixer_add_track_remote
      put 'remove/:jingle_id' => 'mixer#remove_track', as: :mixer_remove_track_remote
    end
  end
  
  # Feed
  get 'feed' => 'feeds#index', as: :feed
  get 'feed/sort/:sort' => 'feeds#index', as: :sorted_feed
  
  # Search
  get 'search' => 'search#show', as: :search
  get 'search/:q' => 'search#show'
  get 'search/:q/sort/:sort' => 'search#show', as: :sorted_search
  
  # Hashtags
  get 'hashtags' => 'hashtags#show', as: :hashtag_base
  get 'hashtags/:tag' => 'hashtags#show', as: :hashtag
  get 'hashtags/:tag/sort/:sort' => 'hashtags#show', as: :sorted_hashtag
  
  # Site
  get 'help' => 'site#help', as: :help
  get 'privacy' => 'site#privacy', as: :privacy
  get 'login_or_register' => 'site#login_or_register', as: :login_or_register
  get 'leave_feedback' => 'site#leave_feedback', as: :leave_feedback
  post 'leave_feedback' => 'site#leave_feedback_create', as: :leave_feedback_create
  # Catch 404 errors
  get '404' => 'site#error_404', as: :error_404
  #get '*path' => 'site#error_404', as: :error_404
  
  # Profiles
  post ':username/follow' => 'followers#toggle', as: :toggle_follow
  post ':username/follow-yes' => 'followers#create', as: :follow
  delete ':username/follow-no' => 'followers#destroy', as: :unfollow
  get ':username/followers' => 'profiles#followers', as: :profile_followers
  get ':username/following' => 'profiles#following', as: :profile_following
  get ':username' => 'profiles#show', as: :profile
  
  
end

app/models/jingle_comment.rb
class JingleComment < ActiveRecord::Base
  include Extends::FollowJingle
  include Extends::NotificationJingle
  include PublicActivity::Model
  
  belongs_to :jingle
  belongs_to :user
  
  tracked owner: ->(controller, model) { model && model.user },
          recipient: ->(controller, model) { model && model.jingle.user }
  
  validates :desc, length: { in: 1..APP_CONFIG["comment_maxlength"] }
  
  after_create  :increment_jingle_comments_count,
                :add_notification,
                :notify_followers
  before_destroy :decrement_jingle_comments_count,
                 :remove_notification,
                 :unfollow_jingle
  
  def too_much_spam?
    user.comments.where(
      "created_at > ?", (Time.now - 30.seconds)
    ).count > 2 ? true : false
  end
  
  def dupe?
    !user.comments.blank? && user.comments.last.desc == self.desc ? true : false
  end
  
  #############
  # Callbacks #
  #############
  def increment_jingle_comments_count
    jingle.update_attribute(:jingle_comments_count, jingle.jingle_comments_count + 1)
  end
  
  def decrement_jingle_comments_count
    jingle.update_attribute(:jingle_comments_count, jingle.jingle_comments_count - 1)
  end
end

app/controllers/jingle_comments_controller.rb
class JingleCommentsController < ApplicationController
  before_filter :authenticate_user!, except: [:comments, :tracks]
  
  helper_method :jingle
  respond_to :html, :js, :json
  
  def comments
    render partial: "jingle_comments/comments"
  end
  
  def tracks
    render partial: "jingle_comments/tracks"
  end
  
  def create
    # TO DO
    # Limit comment posting to only people the current_user is allowed to comment to (since POST jingle_id can be tampered with)
    @comment = JingleComment.new(
      jingle_id: jingle.id,
      user_id: current_user.id,
      desc: jingle_comment_params[:desc]
    )
      
    respond_with(@comment, location: jingle_path(jingle)) do |format|
      unless @comment.too_much_spam? || @comment.dupe?
        if @comment.save
          format.js { render status: :created }
        else
          format.js { render status: :unprocessable_entity, text: "#{t('models.jingle_comment')} #{@comment.errors.first[1]}"}
        end
      else
        if @comment.too_much_spam?
          message = t('jingle_comments.errors.too_many_comments')
        elsif @comment.dupe?
          message = t('jingle_comments.errors.duplicate')
        end
        format.js { render status: :unprocessable_entity, text: message}
      end
    end
  end
  
  def destroy
    
  end

protected
  def jingle
    @jingle ||= Jingle.find(params[:jingle_id])
  end
  
private
  def jingle_comment_params
    params.require(:jingle_comment).permit(:user_id, :jingle_id, :desc)
  end
end

app/helpers/jingle_comments_helper.rb
module JingleCommentsHelper
end

app/views/jingle_comments/_comment.html.haml
%article.comment-item.comment-reply{id: "comment_#{comment.id}"}
  = link_to(image_tag(comment.user.avatar(:small), alt: "", class: "img-circle"), profile_path(comment.user.username), class: "thumb-sm pull-left")
  %span.arrow.left
  %section.comment-body.panel.panel.text-sm
    .panel-body
      %strong= link_to(comment.user.display_name, profile_path(comment.user.username))
      
      = comment.desc
      
      %span.text-muted.m-l-sm.pull-right.date
        %o.icon-time
        = show_time(comment.created_at)

app/views/jingle_comments/_comments.html.haml
.panel-body
  %section.comment-list.block.scrollable{style: "max-height: 200px;"}
    - unless jingle.comments.blank?
      - jingle.comments.each do |comment|
        = render partial: "jingle_comments/comment", locals: {comment: comment}
    - else
      %article.comment-item{style: "display: none;"}
  %footer.panel-footer.pos-rlt.no-border
    - if user_signed_in?
      %span.arrow.top
      = form_tag jingle_contributions_path(jingle), class: "pull-out comment-submit-ajax", data: {jingle: jingle.id}, method: :post, remote: "true" do
        = text_field_tag "jingle_comment[desc]", nil, class: "form-control input-lg text-sm maxlength", placeholder: t('placeholders.add_comment'), maxlength: "200", autocomplete: "off", id: "jingle_comment_desc_#{jingle.id}"
        %span.error_message.bg-danger.label
    - else
      = t('jingle_comments.login_or_register',
        login: link_to(t('buttons.login'), login_path, class: "btn btn-primary btn-xs"),
        register: link_to(t('buttons.register'), register_path, class: "btn btn-default btn-xs")).html_safe

:javascript
  $(document).ready(function() {
    $("#jingle_comment_desc_#{jingle.id}").lilCharacterCount();
  });

app/views/jingle_comments/_original_track.haml
%article.comment-item.comment-reply{id: "track_reply_#{jingle.id}"}
  %section.comment-body.panel.panel.text-sm.bg-light
    .panel-body
      %a.jp-play.btn.btn-xs.btn-info{href: jingle.track.url, id: "play_track_#{jingle.id}", data: {target: "track_#{jingle.id}", waveform: jingle.waveform_url(false), duration: jingle.original_track_duration}}
        %i.icon-play
      %strong= t('jingles.tracks.original')

app/views/jingle_comments/_origins.html.haml
%article.comment-item.comment-reply{id: "track_reply_#{jingle.id}"}
  %section.comment-body.panel.panel.text-sm.bg-light
    .panel-body
      %strong
        = t('jingles.tracks.origin.title', user: "#{link_to(image_tag(origin.jingle.user.avatar(:small), alt: '', class: 'img-circle'), profile_path(origin.jingle.user.username), class: 'thumb-xs pull-left m-r-xs')} #{link_to(origin.jingle.user.display_name, profile_path(origin.jingle.user.username))}", track: link_to(t('jingles.tracks.origin.this_track'), jingle_path(origin.jingle))).html_safe

app/views/jingle_comments/_pending_track.html.haml
%article.comment-item.comment-reply{id: "track_reply_#{jingle.id}"}
  = link_to(image_tag(jingle.user.avatar(:small), alt: "", class: "img-circle"), profile_path(jingle.user.username), class: "thumb-sm pull-left")
  
  %span.arrow.left
  %section.comment-body.panel.panel.text-sm.bg-light
    .panel-body
      - if can_edit?(jingle.parent)
        %strong.user
          = link_to(jingle.user.display_name, profile_path(jingle.user.username))
          %span= t('jingles.tracks.pending')
        = icon_link(t('buttons.bno'), {href: confirm_decline_merge_jingle_path(jingle), class: "btn btn-danger btn-sm decline-merge-ajax removeable", data: {toggle: 'ajaxModal'}}, "icon-remove")
        = icon_link(t('buttons.byes'), {href: accept_merge_jingle_path(jingle), class: "btn btn-success btn-sm accept-merge-ajax removeable", data: {method: :put, remote: true, type: "json"}}, "icon-ok")

      - elsif user_signed_in? && !can_edit?(jingle.parent)
        %strong.user= t('jingles.tracks.pending_sent', user: link_to(jingle.parent.user.display_name, profile_path(jingle.parent.user.username))).html_safe
        
      %span.text-muted.m-l-sm.pull-right.date
        %o.icon-time
        = link_to(show_time(jingle.created_at), jingle_path(jingle))
      
      .jquery_jplayer{id: "track_#{jingle.id}"}
      %a.jp-play.btn.btn-xs.btn-info{href: jingle.parent.merge_url(jingle), id: "play_track_#{jingle.id}", data: {target: "track_#{jingle.id}"}}
        %i.icon-play
      = hashtag_auto_link(jingle.desc)

      /:javascript
      /  track_#{jingle.id}_json = {
      /    id: #{jingle.id},
      /    href: "#{jingle.track.url}"
      /  }

:javascript
  $(document).ready(function() {
    $('[data-toggle="ajaxModal"]').on('click',
      function(e) {
        e.preventDefault();
        var $this = $(this)
          , $remote = $this.attr('href') || $this.data('remote')
          , $modal = $('<div class="modal fade in" id="ajaxModal"><div class="modal-body"></div></div>');
        $('body').append($modal);
        $modal.modal();
        $modal.load($remote);
      }
    );
  });

app/views/jingle_comments/_track.html.haml
%article.comment-item.comment-reply{id: "track_reply_#{jingle.id}"}
  = link_to(image_tag(jingle.user.avatar(:small), alt: "", class: "img-circle"), profile_path(jingle.user.username), class: "thumb-sm pull-left")
  
  %span.arrow.left
  %section.comment-body.panel.panel.text-sm
    .panel-body
      %strong
        = t('jingles.tracks.added', added_by: link_to(jingle.user.display_name, profile_path(jingle.user.username)), track_by: link_to(jingle.user.display_name, profile_path(jingle.user.username))).html_safe
      %span.text-muted.m-l-sm.pull-right.date
        %o.icon-time
        = link_to(show_time(jingle.created_at), jingle_path(jingle))
      .block
        %a.jp-play.btn.btn-xs.btn-info{href: jingle.track.url, id: "play_track_#{jingle.id}", data: {target: "track_#{jingle.id}", waveform: jingle.waveform_url, duration: jingle.track_duration}}
          %i.icon-play
        = hashtag_auto_link(jingle.desc)
      

app/views/jingle_comments/_track_decline_comment_form.html.haml
= form_tag decline_merge_jingle_path(jingle), id: "decline_jingle_#{jingle.id}", class: "pull-out decline-merge-submit-ajax", data: {jingle: jingle.id}, method: :put do
  = text_field_tag "reason", nil, class: "form-control input-lg text-sm maxlength", placeholder: t('placeholders.add_comment'), maxlength: "200", autocomplete: "off", id: "jingle_merge_#{jingle.id}"

:javascript
  $(document).ready(function() {
    $("#jingle_merge_#{jingle.id}").lilCharacterCount();
    
    $(".modal-submit").on('click', function(e) {
      e.preventDefault();
      $("#decline_jingle_#{jingle.id}").submit();
    });
  });

app/views/jingle_comments/_tracks.html.haml
.panel-body
  %section.comment-list.block.scrollable.tracks.m-b{style: "max-height: 200px;"}
    - if jingle.has_origins?
      - jingle.origins.each do |origin|
        = render partial: "jingle_comments/origins", locals: {origin: origin}
    - if jingle.has_children?
      = render partial: "jingle_comments/original_track", locals: {jingle: jingle}
      - if can_edit?(jingle)
        - jingle.jingles.pending.each do |track|
          = render partial: "jingle_comments/pending_track", locals: {jingle: track}
      - elsif user_signed_in? && !can_edit?(jingle)
        - jingle.pending_child_jingles_for(current_user).each do |track|
          = render partial: "jingle_comments/pending_track", locals: {jingle: track}
      
      - jingle.jingles.merged.each do |track|
        = render partial: "jingle_comments/track", locals: {jingle: track}
    - else
      %strong.text-muted.text-xs= t('jingles.tracks.empty')
        
  %ul.nav.nav-pills
    %li= icon_link(t('buttons.collaborate'), {href: new_jingle_track_jingle_path(jingle), class: "bg-light lt"}, "icon-plus m-r-xs")
    %li= icon_link(t('buttons.mixer'), {href: "#", class: "add-to-mixer bg-light lt"}, "icon-beaker m-r-xs")
      

- if user_signed_in?
  :javascript
    $(document).ready(function() {
      $(".add-to-mixer").click(function(e) {
        e.preventDefault();
        $("#jingle_#{jingle.id} section .track-img").effect("transfer", { to: "#track-mixer span:last-child" }, 250);

        $.ajax({
          url: "#{mixer_add_track_remote_mixer_index_path}",
          data: "jingle_id=#{jingle.id}",
          type: "PUT",
          context: document.body
        }).success(function(data) {
          $("#track-mixer").append(data);
        });
      });
    });

app/views/jingle_comments/create.js.erb
$("<%= escape_javascript(render partial: 'jingle_comments/comment', locals: {comment: @comment}, object: @comment) %>").insertAfter("#comments_<%= @comment.jingle.id %> .comment-list .comment-item:last").effect("highlight", {}, 4000);
var $comments_container = $("#comments_<%= @comment.jingle.id %> .comment-list");
var $comment_form = $("#jingle_comment_desc_<%= @comment.jingle.id%>");
var $comment_count_container = $("#comments_count_<%= @comment.jingle.id %> span");
var comment_count = parseInt($comment_count_container.html()) + 1;

$comments_container.slimScroll({ scrollTo: ($comments_container.prop('scrollHeight') + 200) });
$comment_count_container.html(comment_count);
$comment_form.val("");
$comment_form.parent().children(".character-count").html("200");