config/routes.rb
Jinglr::Application.routes.draw do
  root 'site#index'
  
  # Devise auth
  devise_for :users, controllers: {
    sessions: 'sessions',
    registrations: 'registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  devise_scope :user do
    delete 'logout' => 'sessions#destroy', as: :logout
    get 'login' => 'sessions#new', as: :login
    get 'register' => 'registrations#new', as: :register
    # Check for existence of username
    get 'username_check' => 'registrations#username_check', as: :username_check
  end
  
  # Users
  resources :user, controller: :users do
    resources :details, controller: :user_details
    
    member do
      post :upload_avatar
      delete :delete_avatar
      put :update_email
      put :update_password
      get :select_username
      put :set_username
    end
    
    collection do
      get :jingles
      get :favorites, controller: :jingle_favorites, to: :index
      get :notifications, controller: :notifications, to: :index
      get :followers, controller: :followers, to: :followers
      get :following, controller: :followers, to: :following
    end
  end
  
  # User home
  get 'user/jingles' => 'users#jingles', as: :home
  
  # Notificaitons in header
  get 'user/notifications/remote' => 'notifications#remote', as: :remote_notifications
  get 'user/notification/:id/remote' => 'notifications#remote_notification', as: :remote_notification
  # Mark notifications as viewed
  put 'user/notifications/view' => 'notifications#mark_all_viewed', as: :mark_notifications_viewed
  put 'user/notification/:id/view' => 'notifications#mark_viewed', as: :mark_notification_viewed
  put 'user/notifications/settings/update' => 'notifications#update_settings', as: :update_settings_notification
  
  # Jingles
  resources :jingles do
    resources :contributions, controller: :jingle_comments, only: [:index, :create, :destroy] do
      collection do
        get 'comments' => 'jingle_comments#comments', as: :comments
        get 'tracks' => 'jingle_comments#tracks', as: :tracks
      end
    end
    
    resources :likes, controller: :jingle_likes, only: [:create, :destroy] do
      collection do
        post :toggle
      end
    end
    resources :favorites, controller: :jingle_favorites, only: [:create, :destroy] do
      collection do
        post :toggle
      end
    end
    
    collection do
      post :add
      post :merge
      #get 'check-status' => 'jingles#check_status', as: :check_status
      #get 'merge-remote' => 'jingles#merge_remote', as: :merge_remote
      get 'new/:option' => 'jingles#new', as: :new_remote
      get 'sort/:sort' => 'jingles#index', as: :sorted
    end
    
    member do
      post 'toggle-follow' => 'jingles#toggle_follow', as: :toggle_follow
      put 'accept', as: :accept_merge
      put 'decline', as: :decline_merge
      get 'decline-confirm' => 'jingles#confirm_decline_merge', as: :confirm_decline_merge
      get 'check-status' => 'jingles#check_status', as: :check_status
      get 'check-track-status' => 'jingles#check_track_status', as: :check_track_status
      get 'merge-remote' => 'jingles#merge_remote', as: :merge_remote
      get 'add-track-remote' => 'jingles#add_track_remote', as: :add_track_remote
      get 'connections' => 'jingles#connections', as: :connections
      get 'new', as: :new_jingle_track
      get ':open' => 'jingles#show', as: :open
    end
  end
  
  # Track mixer
  resources :mixer, only: [:index, :show] do
    collection do
      get 'get/:jingle_id' => 'mixer#get_track', as: :mixer_get_track_remote
      put 'add' => 'mixer#add_track', as: :mixer_add_track_remote
      put 'remove/:jingle_id' => 'mixer#remove_track', as: :mixer_remove_track_remote
    end
  end
  
  # Feed
  get 'feed' => 'feeds#index', as: :feed
  get 'feed/sort/:sort' => 'feeds#index', as: :sorted_feed
  
  # Search
  get 'search' => 'search#show', as: :search
  get 'search/:q' => 'search#show'
  get 'search/:q/sort/:sort' => 'search#show', as: :sorted_search
  
  # Hashtags
  get 'hashtags' => 'hashtags#show', as: :hashtag_base
  get 'hashtags/:tag' => 'hashtags#show', as: :hashtag
  get 'hashtags/:tag/sort/:sort' => 'hashtags#show', as: :sorted_hashtag
  
  # Site
  get 'help' => 'site#help', as: :help
  get 'privacy' => 'site#privacy', as: :privacy
  get 'login_or_register' => 'site#login_or_register', as: :login_or_register
  get 'leave_feedback' => 'site#leave_feedback', as: :leave_feedback
  post 'leave_feedback' => 'site#leave_feedback_create', as: :leave_feedback_create
  # Catch 404 errors
  get '404' => 'site#error_404', as: :error_404
  #get '*path' => 'site#error_404', as: :error_404
  
  # Profiles
  post ':username/follow' => 'followers#toggle', as: :toggle_follow
  post ':username/follow-yes' => 'followers#create', as: :follow
  delete ':username/follow-no' => 'followers#destroy', as: :unfollow
  get ':username/followers' => 'profiles#followers', as: :profile_followers
  get ':username/following' => 'profiles#following', as: :profile_following
  get ':username' => 'profiles#show', as: :profile
  
  
end

app/controllers/jingles_controller.rb
class JinglesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show, :connections]
  include ApplicationHelper
  include Extends::Normalizer
  helper_method :jingle, :jingles
  respond_to :html, :js, :json
  
  #########
  # Pages #
  #########
  def index
    @hashtags = Jingle.latest_tags
    if params[:partial]
      render partial: "jingles/jingles", locals: {jingles: jingles, bypass_header: params[:page] ? true : false}
    end
  end
  
  def show
    
  end
  
  def new
    @new_jingle = Jingle.new
    
    if params[:option] == 'remote'
      render_modal(t('jingles.new.title'), "jingles/form", new_jingle_path)
    end
  end
  
  def edit
  
  end
  
  
  ########
  # CRUD #
  ########
  def create
    @new_jingle = current_user.jingles.create(jingle_params)
    
    respond_to do |format|
		  if @new_jingle.save
        format.html {
          render json: [@new_jingle.to_jq_upload].to_json,
          content_type: 'text/html',
          layout: false
        }
        format.json { render json: [@new_jingle.to_jq_upload].to_json, status: :created, location: @new_jingle }
      else
        #@file.errors[:partial_refresh_url] = files_upload_product_path(@file.product_id)
        errors = t('flash.alert.jingle_upload') #format_errors_for_js(@new_jingle.errors.full_messages)
        format.html { render action: "new" }
        format.json { render json: errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
  
  end
  
  def destroy
    jingle_id = jingle.id
    respond_to do |format|
      if can_edit?(jingle) && jingle.destroy
        format.html { redirect_to jingles_path, notice: t('flash.notice.destroy', item: t('models.jingle'))}
        format.js {}
        format.json { render json: {jingle_id: jingle_id} }
      else
        format.html { redirect_to jingle_path(jingle), alert: t('flash.notice.destroy', item: t('models.jingle'))}
        format.js { render text: t('flash.alert.destroy', item: t('models.jingle')), status: :unprocessable_entity }
      end
    end
  end
  
  def add
    if jingle_params[:tracks]
      params[:jingle][:tracks].each do |k,v|
        if k.to_i == jingle.parent.id
          jingle.parent_offset = v
        elsif k.to_i == jingle.id
          jingle.child_offset = v
        end
      end
      
    end
    
    # Add desc and activate
    current_user.tag(jingle, with: extract_hashtags(params[:jingle][:desc]), on: :hashtags)
    redirect_path = jingle.has_parent? ? open_jingle_path(jingle.parent, open: "tracks") : jingles_user_index_path
    
    respond_to do |format|
      if can_edit?(jingle) && jingle.activate(params[:jingle][:desc]) #jingle.can_merge_track?(params[:force])
        format.html { redirect_to redirect_path, notice: t("flash.notice.create", item: jingle.class)}
        format.js {}
      else
        format.html { redirect_to new_jingle_path }
        format.js {}
      end
    end
    
    rescue NoMethodError
      nice_try
  end
  
  # Track mixer merge to create new track
  def merge
    # Add desc and activate
    @new_jingle = current_user.jingles.create
    current_user.tag(@new_jingle, with: extract_hashtags(params[:jingle][:desc]), on: :hashtags)
    redirect_path = jingles_user_index_path #jingle.has_parent? ? open_jingle_path(jingle.parent, open: "tracks") : jingles_user_index_path
    
    respond_to do |format|
      if @new_jingle.delay.create_from_origin(params[:jingle]) #jingle.can_merge_track?(params[:force])
        format.html { redirect_to redirect_path, notice: t("flash.notice.create", item: @new_jingle.class)}
        format.js {}
      else
        format.html { render action: "new" }
        format.js {}
      end
    end
  end
  
  def toggle_follow
    unless current_user.following?(jingle)
      respond_with(jingle, location: jingle_path(jingle)) do |format|
        if current_user.follow(jingle)
          format.js { render text: t('flash.notice.follow_jingle'), status: :created }
          format.json { render json: {jingle_id: jingle.id, message: t('flash.notice.follow_jingle')} }
        else
          format.js { render nothing: true, status: :unprocessable_entity }
        end
      end
    else
      respond_with(jingle) do |format|
        if current_user.stop_following(jingle)
          format.js { render text: t('flash.notice.unfollow_jingle'), status: :ok }
          format.json { render json: {jingle_id: jingle.id, message: t('flash.notice.unfollow_jingle')} }
        else
          format.js { render nothing: true, status: :unprocessable_entity }
        end
      end
    end
  end  
  
  ##########
  # Remote #
  ##########
  
  def merge_remote
    render partial: "jingles/mixing_mode", locals: {jingle: jingle}
  end
  
  def add_track_remote
    if jingle.complete?
      render partial: "mixer/track", locals: {jingle: jingle, i: 1}
    else
      render partial: "mixer/track_processing", locals: {jingle: jingle}
    end
  end
  
  # Checks the status of the jingle, to see whether it has been merged or not
  def check_status
    #processing = current_user.jingles.processing
    #parent_state = jingle.has_parent?
    if jingle.merges_processed?(!jingle.has_parent?) && jingle.active?
      render status: :created, text: jingles_user_index_path #, notice: t('flash.notice.create', item: t('models.jingle'))
    else
      render text: "Processing..."
    end
  end
  
  # Checks the status of the jingle, to see whether it has generated so it can go in the add track mixer
  def check_track_status
    #processing = current_user.jingles.processing
    if jingle.complete?
      render status: :created
    else
      render status: 102
    end
  end
  
  # Connections
  def connections
    render partial: "jingles/connections", locals: {jingle: jingle}
  end
  
  
  ##################
  # Merging tracks #
  ##################
  def accept
    respond_to do |format|
      if can_edit?(jingle.parent) && jingle.parent.accept_merge!(jingle)
        format.html { redirect_to open_jingle_path(jingle.parent, open: "tracks"), notice: t('flash.notice.accept_merge') }
        format.js { render status: :created }
        format.json { render json: {jingle_id: jingle.id, message: t('flash.notice.accept_merge')} }
      else
        format.html { redirect_to open_jingle_path(jingle.parent, open: "tracks"), alert: t('flash.alert.accept_merge') }
        format.js { render status: :unprocessable_entity }
        format.json { render json: {jingle_id: jingle.id, message: t('flash.alert.accept_merge')} }
      end
    end
  end
  
  def confirm_decline_merge
    render_modal(t('jingles.tracks.decline.title'), "jingle_comments/track_decline_comment_form", decline_merge_jingle_path(jingle))
  end
  
  def decline
    parent = jingle.parent
    respond_to do |format|
      if can_edit?(jingle.parent) && jingle.parent.decline_merge!(jingle, params[:reason])
        format.html { redirect_to open_jingle_path(parent, open: "tracks"), notice: t('flash.notice.decline_merge') }
        format.js { render text: "#{t('flash.notice.decline_merge')}", status: :ok }
      else
        format.html { redirect_to open_jingle_path(jingle.parent, open: "tracks"), alert: t('flash.alert.decline_merge') }
        format.js { render text: t('flash.alert.decline_merge'), status: :unprocessable_entity }
      end
    end
  end
  
protected

  def jingle
    begin
      if params[:option] == 'remote'
        @jingle = nil
      else
        @jingle ||= Jingle.find((params[:id] || params[:jingle][:parent_id]))
      end
    rescue ActiveRecord::RecordNotFound
      routing_error
    end
  end
  
  def jingles
    if params[:sort]
      start_at = Time.now - 1.month
      end_at   = Time.now
      start_at = normalize_sort_time(params[:from]) if params[:from]
      end_at = normalize_sort_time(params[:to]) if params[:to]
      
      if params[:sort] == "favorites"
        @jingles ||= Jingle.most_favorites(start_at, end_at).page(params[:page])
      elsif params[:sort] == "likes"
        @jingles ||= Jingle.most_likes(start_at, end_at).page(params[:page])
      end
    else
      @jingles ||= Jingle.active.newest.page(params[:page])
    end
  end
  
private
  
  # If they try something slick, like forcing their way through disabled buttons to submit a form
  def nice_try
    redirect_to jingles_path, alert: t('flash.alert.nice_try')
  end
  
  def jingle_params
    params.require(:jingle).permit(
      :user_id,
      :parent_id,
      :desc,
      :track_file_name,
      :track_content_type,
      :track_file_size,
      :track_updated_at,
      :track,
      :force_create,
      :child_offset,
      :parent_offset,
      :tracks => {}
    )
  end
end

app/helpers/jingles_helper.rb
module JinglesHelper

  def jingle_track_list(jingle)
    output = ""
    jingle.jingles.each do |track|
      output += (track.id.to_s + ",")
    end
    return output
  end
  
  def jingle_connection_icon(jingle)
    icon = ""
    case jingle.connection_type
      when "origin"
        icon = "icon-beaker bg-primary"
      when "origin_master"
        icon = "icon-beaker bg-info"
      when "parent"
        icon = "icon-music bg-info"
      when "child"
        icon = "icon-plus bg-success"
    end
    
    content_tag(:i, '', class: "time-icon #{icon}", title: t("jingles.connections.#{jingle.connection_type}"), data: {toggle: "tooltip"})
  end
end

app/views/jingles/_add_track_form.html.haml
#mixer
  .panel
    .panel-body.scrollable
      = render partial: "mixer/track", locals: {jingle: jingle, i: 0}
    %i.icon-arrow-right.pull-right.mixer-scroll-right
    %i.icon-arrow-left.pull-left.mixer-scroll-left{style: "display: none;"}
    .panel-body.text-center
      = icon_link("", {href: "#", class: "btn btn-info btn-lg track-play"}, "icon-play")

:javascript
  $(document).ready(function() {
    fade_in_images();
  });

app/views/jingles/_connections.html.haml
- if jingle.connections.blank?
  %section.panel.no-borders.hbox
    %aside.bg-danger.clearfix.lter.r-r.text-right.v-middle
      .wrapper.h3.font-thin
        = t('jingles.connections.empty_head')
    %aside
      .pos-rlt
        %span.arrow.left.hidden-xs
        .panel-body
          = t('jingles.connections.empty').html_safe
- else
  .timeline
    - jingle.connections.each do |connection|
      %article.timeline-item
        .timeline-caption
          .panel
            .panel-body
              %span.arrow.left
              %span.timeline-icon
                %a{href: jingle_path(connection)}
                  = jingle_connection_icon(connection)
              %span.timeline-date= link_to(show_time(connection.created_at), jingle_path(connection))
              %h5
                %span.user
                  = image_tag(connection.user.avatar(:small), alt: connection.user.display_name, class: "thumb-xs img-circle pull-left m-r-xs")
                  = link_to(connection.user.display_name, profile_path(connection.user.username))
                = hashtag_auto_link(connection.desc)

:javascript
  $(function() {
    $("[data-toggle=tooltip]").tooltip();
  });

app/views/jingles/_form.html.haml
- if @new_jingle.errors.present?
  #error_explanation
    %h2= t('flash.error', count: @new_jingle.errors.count)
    %ul
      - @new_jingle.errors.full_messages.each do |msg|
        %li= msg

.abox.new_jingle_form
  %section.panel.no-borders.hbox
    %aside.bg-info.clearfix.lter.r-r.text-right.v-middle.message_box#jingle_alerts
      .wrapper.h3.font-thin
        - unless jingle.blank?
          = t('jingles.new.add_track')
        - else
          = t('jingles.new.title')
    %aside
      .pos-rlt
        %span.arrow.left.hidden-xs
        .panel-body                  
          %section.panel.m-n
            = form_tag add_jingles_path, id: "new_jingle_form", remote: true, method: :post do
              = hidden_field_tag "id"
              - unless jingle.blank?
                = hidden_field_tag "jingle[parent_id]", jingle.id
              %textarea.form-control.input-lg.no-border{rows: "4", maxlength: "200",
                placeholder: t('jingles.new.describe'), id: "jingle_desc", name: "jingle[desc]"}
              
              %footer.panel-footer.bg-light.lter
                - unless params[:option] == 'remote'
                  %button.btn.btn-success.pull-right.disabled#submit-jingle-button{type: "submit"}= t('buttons.compose')
                %ul.nav.nav-pills
                  /%li#file-recorder
                  /  %a{href: "#"}
                  /    %i.icon-microphone
                  /    = t('jingles.new.record')
                  %li.file-uploader
                    /= form.file_field :track
                    %a.fileinput-button{href: "javascript:void(0)"}
                      %i.icon-upload
                      = t('jingles.new.upload')
                      = file_field_tag "jingle[track]", data: {target: jingles_path, errorbox: "#jingle_alerts", error: t('flash.alert.jingle_upload')}
                  %li.file-uploader-details
                    .uploader
                      #progress.progress.progress-sm.progress-striped.active.new-jingle-progress{style: "display: none;"}
                        .progress-bar.progress-bar-success
                      #successful-upload.text-success{style: "display: none;"}
                        %i.icon-check
                      #files.files

- if params[:option] == 'remote'
  :javascript
    $(document).ready(function() {
      initialize_jingles_js();
      $("#jingle_desc").lilCharacterCount();
      
      $(".modal-submit").on('click', function(e) {
        e.preventDefault();
        $("#new_jingle_form").submit();
      });
    });

app/views/jingles/_jingle.html.haml
%section.panel.panel-short.draggable{data: {path: mixer_add_track_remote_mixer_index_path, jingle: jingle.id}}
  - if jingle.waveform_url
    .track-img.jp-seek-bar
      .progress
      = image_tag(jingle.waveform_url)
  - else
    .track-img.jp-seek-bar{id: "track_img_#{jingle.id}"}
      .progress

    %i.icon-spinner.icon-spin.absolute{id: "spinner_#{jingle.id}"}
      
  .panel-body
    .clearfix
      %small.text-muted.pull-right.date
        %o.icon-time
        = link_to(show_time(jingle.latest_at), jingle_path(jingle))
      = link_to(image_tag(jingle.user.avatar(:small), alt: "", class: "img-circle"), profile_path(jingle.user.username), class: "thumb-sm pull-left m-r")
      .user-details
        %a{href: profile_path(jingle.user.username)}
          %strong= jingle.user.display_name
          
      %a.jp-play.btn.btn-xs.btn-info.pull-left{href: jingle.latest_url, id: "play-btn_#{jingle.id}", data: {target: "track_#{jingle.id}", id: jingle.id, duration: jingle.track_duration, waveform: jingle.waveform_url}}
        %i.icon-play
      .pull-left.col-sm-9.jingle-desc= hashtag_auto_link(jingle.desc)
      

%section.panel.m-b-none
  %header.panel-heading.bg-light
    %ul.nav.nav-tabs.nav-justify.bg-gradient.bg-light
      %li{class: "#{'active' if params[:open] == 'tracks'}"}
        %a.realign-grid.ajax-tab{href: tracks_jingle_contributions_path(jingle), id: "collaborations_count_#{jingle.id}", data: {toggle: "tab", target: "#collaborations_#{jingle.id}"}}
          %i.icon-music
          /= pluralize(jingle.jingle_tracks_count, t('jingles.jingle.collaboration'))
          %span= jingle.jingle_tracks_count
      %li{class: "#{'active' if params[:open] == 'comments'}"}
        %a.realign-grid.ajax-tab{href: comments_jingle_contributions_path(jingle), id: "comments_count_#{jingle.id}", data: {toggle: "tab", target: "#comments_#{jingle.id}"}}
          %i.icon-comments
          /= pluralize(jingle.jingle_comments_count, t('jingles.jingle.comment'))
          %span= jingle.jingle_comments_count
      %li
        %a.realign-grid{href: "javascript:void", id: "options_tab_#{jingle.id}", data: {toggle: "tab", target: "#options_#{jingle.id}"}}
          %i.icon-gear
          
    
    .comment-action.m-t-sm.pull-right
      - if user_signed_in?
        %a.btn.btn-white.btn-xs.like-submit-ajax{href: toggle_jingle_likes_path(jingle),
          title: t('jingles.jingle.like'), data: {toggle: "class", remote: "true", method: :post, jingle: jingle.id},
          class: ('active' if jingle.liked_by?(current_user))}
          %i.icon-thumbs-up.text-muted.text
          %i.icon-thumbs-up.text-info.text-active
          %span{id: "likes_count_#{jingle.id}"}= jingle.jingle_likes_count
        - unless can_edit?(jingle)
          %a.btn.btn-white.btn-xs.favorite{href: toggle_jingle_favorites_path(jingle),
            title: t('jingles.jingle.favorite'), data: {toggle: "class", remote: "true", method: :post},
            class: ('active' if jingle.favorited_by?(current_user))}
            %i.icon-heart.text-muted.text
            %i.icon-heart.text-info.text-active
          %a.btn.btn-white.btn-xs.follow.follow-jingle-submit-ajax{href: toggle_follow_jingle_path(jingle),
            title: t('jingles.jingle.follow'), data: {toggle: "class", remote: "true", method: :post, type: "json"},
            class: ('active' if current_user.following?(jingle))}
            %i.icon-bullhorn.text-muted.text
            %i.icon-bullhorn.text-info.text-active
            
          
  .tab-content
    .tab-pane{id: "collaborations_#{jingle.id}", class: "#{'active' if params[:open] == 'tracks'}"}
              
    .tab-pane{id: "comments_#{jingle.id}", class: "#{'active' if params[:open] == 'comments'}"}
          
    .tab-pane{id: "options_#{jingle.id}"}
      .panel-body
        %ul.nav.nav-pills
          - if jingle.has_parent? && jingle.merged_with?(jingle.parent)
            %li= icon_link(t('buttons.view_parent'), {href: open_jingle_path(jingle.parent, "tracks")}, "icon-code-fork")
          - if 1 == 2 # If user can tweet
            %li= icon_link(t('buttons.services.tweet'), {href: "#"}, "icon-twitter")
          - if user_signed_in? && can_edit?(jingle)
            %li= icon_link(t('buttons.delete'), {href: jingle_path(jingle), data: {method: :delete, remote: :true, confirm: t('confirm.delete', item: t('models.jingle'))}, class: "text-danger"}, "icon-trash")
          %li= icon_link(t('audio_player.view_jingle'), {href: jingle_path(jingle)}, "icon-eye-open")
            

- if params[:open] == 'comments'
  :javascript
    $(document).ready(function() {
      $("#comments_count_#{jingle.id}").trigger("click");
    });
- if params[:open] == 'tracks'
  :javascript
    $(document).ready(function() {
      $("#collaborations_count_#{jingle.id}").trigger("click");
    });

app/views/jingles/_mixing_mode.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %h4.modal-title.text-center= t('jingles.creating.title')
    .modal-body
      .generating_jingle
        %i.icon-spinner.icon-spin
      .did_you_know.well.bg-info
        %h4= t('trivia.title')
        = t("trivia.did_you_know.#{Extends::MixLoader::LOADING_MESSAGES.sample}")

:javascript
  $(document).ready(function() {
    jingleInterval = setInterval(checkJingleStatus, 3000);
    
    function checkJingleStatus() {
      $.get("#{check_status_jingle_path(jingle)}", function(data) {
        console.log(data);
        if (data != "Processing...") {
          window.location = data;
        }
      });
    }
  });

app/views/jingles/add.js.erb
$modal = $('<div class="modal fade" id="ajaxModal"><div class="modal-body"></div></div>');
$('body').append($modal);
$modal.modal({backdrop: "static"});
$modal.load("<%= merge_remote_jingle_path(jingle) %>");

app/views/jingles/destroy.js.erb
// $(".jplayer").jPlayer("stop");
if ($(".file-uploader").length > 0) {
  $("#jingle_<%= @jingle.id %>").remove().delay(300);
  $("li.file-uploader").show();
  $("#submit-jingle-button").addClass("disabled");
  $(".track_1").fadeOut();
  $(".track_1").remove();
  //$tracks[1].remove();
  //delete $tracks[1];
} else {
  $("#jingle_<%= @jingle.id %>").fadeOut("700");
}

app/views/jingles/index.html.haml
- content_for :title do
  = t('jingles.index.title')

- content_for :header do
  %li{class: "#{'active' unless params[:sort]}"}= link_to(t('jingles.index.header.new'), jingles_path)
  %li{class: "#{'active' if params[:sort] == 'likes'}"}= link_to(t('jingles.index.header.most_likes'), sorted_jingles_path(:likes))
  %li{class: "#{'active' if params[:sort] == 'favorites'}"}= link_to(t('jingles.index.header.most_favorites'), sorted_jingles_path(:favorites))

- content_for :browser do
  .list-group.bg-white
    %span.bg-info.list-group-item= t('jingles.index.browser.title')
    - @hashtags.each do |tag|
      %a{href: hashtag_path(tag.name), class: "list-group-item", id: "tag_#{tag.id}"}
        .badge= tag.count
        = hashtag_format(tag.name)

.infinite-page.scrollable#infinite
  = render partial: "jingles", locals: {jingles: jingles, title: t('jingles.index.title')}

app/views/jingles/merge.js.erb
$modal = $('<div class="modal fade" id="ajaxModal"><div class="modal-body"></div></div>');
$('body').append($modal);
$modal.modal({backdrop: "static"});
$modal.load("<%= merge_remote_jingle_path(@new_jingle) %>");

app/views/jingles/show.html.haml
- content_for :title do
  = t('jingles.show.title')

- content_for :header do
  = render partial: "jingles/tour/show"

- content_for :browser do
  .list-group.bg-white
    %span.bg-dark.list-group-item= t('jingles.show.browser.title')
    = icon_link(t('jingles.show.browser.add_track'), {href: new_jingle_track_jingle_path(jingle), class: "list-group-item add-track"}, "icon-plus m-r")
    = icon_link(t('jingles.show.browser.add_to_mixer'), {href: "#", class: "list-group-item add-to-mixer"}, "icon-beaker m-r")
    = icon_link(t('jingles.show.browser.view_tree'), {href: connections_jingle_path(jingle), class: "list-group-item view-connections ajax-tab", data: {target: "#connections"}}, "icon-sitemap m-r")

/-# jingle.normalized_offsets.each do |a|
/  %p #{a.id} - #{a.offset}
/=# jingle.combine_tracks
.col-md-12.jingle.m-t{id: "jingle_#{jingle.id}"}
  = render partial: "jingle", locals: {jingle: jingle}
  #connections
  

:javascript
  $(document).ready(function() {
    fade_in_images();
  });
  
- if user_signed_in?
  :javascript
    $(document).ready(function() {
      $(".add-to-mixer").click(function(e) {
        e.preventDefault();
        $("#jingle_#{jingle.id} section .track-img").effect("transfer", { to: "#track-mixer span:last-child" }, 250);

        $.ajax({
          url: "#{mixer_add_track_remote_mixer_index_path}",
          data: "jingle_id=#{jingle.id}",
          type: "PUT",
          context: document.body
        }).success(function(data) {
          $("#track-mixer").append(data);
        });
      });
    });